import { warmup } from "./config";
import { generateHeston, TrackKind } from "./heston";
import { ModelName, runNamed, scoreRun, Score } from "./models";
import { EngineOutput } from "./pipeline";
import fixtureA1Gated from "./published/lab_fixture_a1_gated.json";
import fixtureA1Ungated from "./published/lab_fixture_a1_ungated.json";
import fixtureA2Gated from "./published/lab_fixture_a2_gated.json";
import fixtureA2Ungated from "./published/lab_fixture_a2_ungated.json";
import fixtureA3Gated from "./published/lab_fixture_a3_gated.json";
import fixtureA3Ungated from "./published/lab_fixture_a3_ungated.json";

export type LabPoint = EngineOutput & {
  t: number;
  latent: number;
  price: number;
  jump: boolean;
  regime: boolean;
};

type FixtureRow = {
  y: number; latent: number; price: number; p_hat: number; v_hat: number;
  R: number; sa2: number; rho: number; nis_a: number; nis_s: number;
  nu: number; gamma: number; cusum: number; alarm: boolean;
  action: "TRADE" | "HOLD"; ready: boolean; jump: boolean; regime: boolean;
};

type Fixture = {
  n: number; track: string; seed: number; gated: boolean; warmup: number;
  generated_by: string; series: FixtureRow[];
};

const FIXTURES: Record<string, Fixture> = {
  A1_gated: fixtureA1Gated as Fixture,
  A1_ungated: fixtureA1Ungated as Fixture,
  A2_gated: fixtureA2Gated as Fixture,
  A2_ungated: fixtureA2Ungated as Fixture,
  A3_gated: fixtureA3Gated as Fixture,
  A3_ungated: fixtureA3Ungated as Fixture,
};

function toLabPoint(r: FixtureRow, t: number): LabPoint {
  return {
    ready: r.ready,
    action: r.action,
    y: r.y,
    pHat: r.p_hat,
    vHat: r.v_hat,
    Rt: r.R,
    sa2: r.sa2,
    rho: r.rho,
    nisAdapt: r.nis_a,
    nisShadow: r.nis_s,
    nu: r.nu,
    gamma: r.gamma,
    cusum: r.cusum,
    alarm: r.alarm,
    details: [],
    t,
    latent: r.latent,
    price: r.price,
    jump: r.jump,
    regime: r.regime,
  };
}

/**
 * The lab replays a committed fixture generated by the Python engine
 * (scripts/reproduce_results.py -> traces_for_dashboard). It does not
 * simulate live and its output is a demo, not citable evidence.
 */
export function runLab(n = 1400, track: TrackKind = "A2", seed = 42, gated = true) {
  void seed;
  const key = `${track}_${gated ? "gated" : "ungated"}`;
  const fx = FIXTURES[key] ?? FIXTURES["A2_gated"];
  const rows = fx.series.slice(0, Math.max(1, Math.min(n, fx.series.length)));
  const series = rows.map((r, t) => toLabPoint(r, t));
  return {
    series,
    warmup: fx.warmup,
    track,
    n: series.length,
    fixture: true,
    generatedBy: fx.generated_by,
  };
}

export function runLadder(n = 1100, track: TrackKind = "A2", seed = 42): Score[] {
  const path = generateHeston(n, track, seed);
  const names: ModelName[] = ["M0", "M1", "M2", "M5", "M6", "M7", "M8", "M9", "M5'"];
  return names.map((name) => {
    const run = runNamed(name, path.price);
    const nis = (run as { nis?: number[] }).nis;
    return scoreRun(run, path.logObs, path.latent, nis);
  });
}

export { warmup };
